services:
  remix-dev-frontend-1:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    ports:
      - 4100:3000
    restart: always

  remix-dev-frontend-2:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    ports:
      - 4130:3000
    restart: always

