import { Article } from "./api-call";
import image1 from "./dummy-images/image 1.svg";
import image2 from "./dummy-images/image 2.svg";
import image3 from "./dummy-images/image 3.svg";
import image5 from "./dummy-images/image 5.svg";
import authorImage from "./dummy-images/image author.svg";

export const dummyArticles: Article[] = [
  {
    id: "1",
    title: "5 Mistakes That Kill Your Start-up Before It Takes Off",
    description:
      "We often hear about the ENIAC, hailed as the first computer, but its story is just one thread in a rich tapestry woven by brilliant minds.",
    profileImage: authorImage,
    name: "Nora Nora",
    time: "5 min",
    creationDate: "July 12, 2024",
    image: image1,
    link: "/articles/1",
    tag: "Business",
  },
  {
    id: "2",
    title: "The Evolution of Programming Languages",
    description:
      "A comprehensive look at how programming languages have evolved over the decades and their impact on software development.",
    profileImage: authorImage,
    name: "John Doe",
    time: "7 min",
    creationDate: "July 13, 2024",
    image: image2,
    link: "/articles/2",
    tag: "Education",
  },
  {
    id: "3",
    title: "The Future of Remote Work",
    description:
      "Exploring trends and predictions for the future of remote work and how businesses can adapt to new ways of working.",
    profileImage: authorImage,
    name: "Jane Smith",
    time: "6 min",
    creationDate: "July 14, 2024",
    image: image3,
    link: "/articles/3",
    tag: "Business",
  },
  {
    id: "4",
    title: "Innovations in Artificial Intelligence",
    description:
      "An overview of recent advancements in AI technology and their implications for various industries.",
    profileImage: authorImage,
    name: "John Doe",
    time: "8 min",
    creationDate: "July 15, 2024",
    image: image2,
    link: "/articles/4",
    tag: "Education",
  },
  {
    id: "5",
    title: "Effective Marketing Strategies for 2024",
    description:
      "A guide to the most effective marketing strategies and tactics that businesses should consider in 2024.",
    profileImage: authorImage,
    name: "Bob Brown",
    time: "4 min",
    creationDate: "July 16, 2024",
    image: image5,
    link: "/articles/5",
    tag: "Business",
  },
  {
    id: "6",
    title: "5 Mistakes That Kill Your Start-up Before It Takes Off",
    description:
      "We often hear about the ENIAC, hailed as the first computer, but its story is just one thread in a rich tapestry woven by brilliant minds.",
    profileImage: authorImage,
    name: "Nora Nora",
    time: "5 min",
    creationDate: "July 12, 2024",
    image: image1,
    link: "/articles/6",
    tag: "Business",
  },
  {
    id: "7",
    title: "The Evolution of Programming Languages",
    description:
      "A comprehensive look at how programming languages have evolved over the decades and their impact on software development.",
    profileImage: authorImage,
    name: "John Doe",
    time: "7 min",
    creationDate: "July 13, 2024",
    image: image2,
    link: "/articles/7",
    tag: "Education",
  },
  {
    id: "8",
    title: "The Future of Remote Work",
    description:
      "Exploring trends and predictions for the future of remote work and how businesses can adapt to new ways of working.",
    profileImage: authorImage,
    name: "Jane Smith",
    time: "6 min",
    creationDate: "July 14, 2024",
    image: image3,
    link: "/articles/8",
    tag: "Business",
  },
  {
    id: "9",
    title: "Innovations in Artificial Intelligence",
    description:
      "An overview of recent advancements in AI technology and their implications for various industries.",
    profileImage: authorImage,
    name: "John Doe",
    time: "8 min",
    creationDate: "July 15, 2024",
    image: image2,
    link: "/articles/9",
    tag: "Education",
  },
  {
    id: "10",
    title: "Effective Marketing Strategies for 2024",
    description:
      "A guide to the most effective marketing strategies and tactics that businesses should consider in 2024.",
    profileImage: authorImage,
    name: "Bob Brown",
    time: "4 min",
    creationDate: "July 16, 2024",
    image: image5,
    link: "/articles/10",
    tag: "Business",
  },
  {
    id: "11",
    title: "5 Mistakes That Kill Your Start-up Before It Takes Off",
    description:
      "We often hear about the ENIAC, hailed as the first computer, but its story is just one thread in a rich tapestry woven by brilliant minds.",
    profileImage: authorImage,
    name: "Nora Nora",
    time: "5 min",
    creationDate: "July 12, 2024",
    image: image1,
    link: "/articles/11",
    tag: "Business",
  },
  {
    id: "12",
    title: "The Evolution of Programming Languages",
    description:
      "A comprehensive look at how programming languages have evolved over the decades and their impact on software development.",
    profileImage: authorImage,
    name: "John Doe",
    time: "7 min",
    creationDate: "July 13, 2024",
    image: image2,
    link: "/articles/12",
    tag: "Education",
  },
  {
    id: "13",
    title: "The Future of Remote Work",
    description:
      "Exploring trends and predictions for the future of remote work and how businesses can adapt to new ways of working.",
    profileImage: authorImage,
    name: "Jane Smith",
    time: "6 min",
    creationDate: "July 14, 2024",
    image: image3,
    link: "/articles/13",
    tag: "Business",
  },
  {
    id: "14",
    title: "Innovations in Artificial Intelligence",
    description:
      "An overview of recent advancements in AI technology and their implications for various industries.",
    profileImage: authorImage,
    name: "John Doe",
    time: "8 min",
    creationDate: "July 15, 2024",
    image: image2,
    link: "/articles/14",
    tag: "Education",
  },
  {
    id: "15",
    title: "Effective Marketing Strategies for 2024",
    description:
      "A guide to the most effective marketing strategies and tactics that businesses should consider in 2024.",
    profileImage: authorImage,
    name: "Bob Brown",
    time: "4 min",
    creationDate: "July 16, 2024",
    image: image5,
    link: "/articles/15",
    tag: "Business",
  },
  {
    id: "16",
    title: "5 Mistakes That Kill Your Start-up Before It Takes Off",
    description:
      "We often hear about the ENIAC, hailed as the first computer, but its story is just one thread in a rich tapestry woven by brilliant minds.",
    profileImage: authorImage,
    name: "Nora Nora",
    time: "5 min",
    creationDate: "July 12, 2024",
    image: image1,
    link: "/articles/16",
    tag: "Business",
  },
  {
    id: "17",
    title: "The Evolution of Programming Languages",
    description:
      "A comprehensive look at how programming languages have evolved over the decades and their impact on software development.",
    profileImage: authorImage,
    name: "John Doe",
    time: "7 min",
    creationDate: "July 13, 2024",
    image: image2,
    link: "/articles/17",
    tag: "Education",
  },
  {
    id: "18",
    title: "The Future of Remote Work",
    description:
      "Exploring trends and predictions for the future of remote work and how businesses can adapt to new ways of working.",
    profileImage: authorImage,
    name: "Jane Smith",
    time: "6 min",
    creationDate: "July 14, 2024",
    image: image3,
    link: "/articles/18",
    tag: "Business",
  },
  {
    id: "19",
    title: "Innovations in Artificial Intelligence",
    description:
      "An overview of recent advancements in AI technology and their implications for various industries.",
    profileImage: authorImage,
    name: "John Doe",
    time: "8 min",
    creationDate: "July 15, 2024",
    image: image2,
    link: "/articles/19",
    tag: "Education",
  },
  {
    id: "20",
    title: "Effective Marketing Strategies for 2024",
    description:
      "A guide to the most effective marketing strategies and tactics that businesses should consider in 2024.",
    profileImage: authorImage,
    name: "Bob Brown",
    time: "4 min",
    creationDate: "July 16, 2024",
    image: image5,
    link: "/articles/20",
    tag: "Business",
  },
];
